# Copyright contributors to the IBM Security Verify Operator project

apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    app: ibm-security-verify-operator
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
    app: ibm-security-verify-operator
