# Copyright contributors to the IBM Security Verify Operator project

# permissions for end users to edit ibmsecurityverifies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibmsecurityverify-editor-role
rules:
- apiGroups:
  - ibm.com
  resources:
  - ibmsecurityverifies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibm.com
  resources:
  - ibmsecurityverifies/status
  verbs:
  - get
