# permissions for end users to view ibmsecurityverifies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibmsecurityverify-viewer-role
rules:
- apiGroups:
  - ibm.com
  resources:
  - ibmsecurityverifies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ibm.com
  resources:
  - ibmsecurityverifies/status
  verbs:
  - get
