# permissions for end users to view verifytenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verifytenant-viewer-role
rules:
- apiGroups:
  - ibm.com
  resources:
  - verifytenants
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ibm.com
  resources:
  - verifytenants/status
  verbs:
  - get
