# permissions for end users to edit verifytenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verifytenant-editor-role
rules:
- apiGroups:
  - ibm.com
  resources:
  - verifytenants
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibm.com
  resources:
  - verifytenants/status
  verbs:
  - get
