# Copyright contributors to the IBM Security Verify Operator project

apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Seamless Upgrades
    categories: Security
    certified: "false"
    containerImage: ibmcom/verify-operator:0000.0000.0000
    createdAt: --date--
    description: The IBM Security Verify operator can consistently enforce policy-driven security, including authentication and authorization, using the Ingress networking capability of OpenShift.
    repository: https://github.com/IBM-Security/verify-operator
    support: IBM
    # Prevent cluster upgrades to OpenShift Version 4.9 when this 
    # bundle is installed on the cluster
    "olm.properties": '[{"type": "olm.maxOpenShiftVersion", "value": "4.8"}]'
  name: ibm-security-verify-operator.v0000.0000.0000
  namespace: placeholder

spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: IBMSecurityVerify is the Schema for the ibmsecurityverifies API
      displayName: IBM Security Verify
      kind: IBMSecurityVerify
      name: ibmsecurityverifies.ibm.com
      version: v1
  description: |+
    [IBM Security Verify](https://www.ibm.com/products/verify-for-workforce-iam) allows IT, security and business leaders to protect their digital users, assets and data in a hybrid multicloud world, while enabling technical agility and operational efficiency as a cloud-native solution. Beyond single sign-on (SSO) and multifactor authentication (MFA), Verify is a modernized, modular IDaaS that provides deep AI-powered context for risk-based authentication and adaptive access decisions, guided experiences for developer consumability and comprehensive cloud IAM capabilities, including user management, access recertification campaigns and identity analytics.

    For a detailed description of IBM Security Verify refer to the [Offical documentation](https://www.ibm.com/docs/en/security-verify).

    The IBM Security Verify operator can consistently enforce policy-driven security by using the Ingress networking capability of OpenShift. With this approach, you can enforce authentication and authorization policies for all of the applications in your cluster at the same time, without ever changing your application code.

    See the project [Readme](https://github.com/IBM-Security/verify-operator/blob/master/README.md) for further information and details.

  displayName: IBM Security Verify Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAFBlWElmTU0AKgAAAAgAAgESAAMAAAABAAEAAIdpAAQAAAABAAAAJgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAQKADAAQAAAABAAAAQAAAAABUjGyuAAABWWlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iWE1QIENvcmUgNi4wLjAiPgogICA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogICAgICA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIgogICAgICAgICAgICB4bWxuczp0aWZmPSJodHRwOi8vbnMuYWRvYmUuY29tL3RpZmYvMS4wLyI+CiAgICAgICAgIDx0aWZmOk9yaWVudGF0aW9uPjE8L3RpZmY6T3JpZW50YXRpb24+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgoZXuEHAAALrUlEQVR4AdVbCWwVxxme2X2HbYQxjQi0DRTaFEFSwqGm0FwURREpl+1ADAZjsDE4RCRp0iZtFLVCadSoVSNaRBvc+MAHBZ7riyt1UUIhBJE2JYDC0aoNaghpgCSYw372e293+v3rXb/1vmv3+eFHRnqe2X9m/uPbf/45dsxZGlJNS0uOFJByGRM/6BXPf6N61LaS/PyOwVaHD6bAhoa92cLd8xDj0iohxAOQPUSX38k5P8iEWsWD3n1FRXOuDpZegwKAYbhgvAyGkeFZMQzsAv0gZ6JysIC4oQA4MNyKx6ABcUMA8Pl8w3qEezbjHK7O7ovxxq+B/lfd8u8hH6qXzVkX5+wQE6LKy4PtBQUFV8yVqSinFADDcMEYXJ2T4ZlRlKTxvQ8xoKp7iOsA1Wd0hmYiBqxC8SH8solmSX4EzENQtjLVQKQEACeGw9DKrkzpYPn8+eTmfali166sLL/6AIChODFoQAwIgFQY3oeAXhhsIJICgOZxV4B9H1G9FHrfi19MV4/1xq2GW5/tA8HexqxRHfKw15NZRzgCIGy4NsbvgdIZVsXxfAXAtJNS/iz5LaurR2kfl0RAZHYp9xPY4DkbjYdF6dCNGHEYxlQ6BcIWAE4MlzgCFes5hIiNwJW6hOGW2cO896mClaUSiLgAQKinW/XmMq4+hqge940nY/j+/ftd584FvMXFszvtQuUECCakzRlSTxteRiAW/7gA1Pl2jWFCeQOdb4/CQHP1ZAw3eFVvax3t4uxFJok3Ayy4p6yg4HOjLlFuE4h/My4/WFww/8NY/FyxKoiuKCFJlri1zWVUtSO4VWcM0NXhyjI8axYTfJmHeQ/X7mipDPLgXjtA6ENsH4A4REMD0ycFZIoRw/EzkotsMB6i5VbjorUx0z6Dsms6st17npwzp8dckXQZKKCvG0FsJmd8hkd4jyQDxMa9ew/mXA3OZVz8AfxusatPXHSiMLkmu0P/SJnxkQK8OhCVAKIZQBRV+nxfimwWSSGdSDfU0BLbdnIKAAsEMOpTlTJYBzzqL2BnPQfoB0Sdr2V5bXNzwreajG6OAUiV7cSHFi6KP/spnA8sxED4I0jWIKgBAZBe4yGpBUCstAOEEx3TCoAGQsms7uKCBW8q/mGrMN0+gjjQEBUIwe4HEBWpBiLtABhvq0QD4pEDl4e6y+IA4YGnpBQIp7OAoe8Ny/UAewBR/UjO9e4ZXMhlgok5EGgOhr1AMD6dh3gphkY11hE7PbIqlBBmVgfppgPA0N0pEB7uKQ2FxD5EaMQN++mmBcAwwQxE9rXgdJmppdgYzUO9eVbQPALxg5brjmaptMaAiooKN50bGsbGywmIlYtzD+JEaA1XWT7WT7Vo/5mlD/m/I5scNbYIG/CjO3vkKNUdqKjb0ba62ucbYYchbWyWF+a9lQAIO6y0NmkFQNsLCPZdrP5+72KeVgKirrn5VjvapwqItAKgGdq7F3BhesP4Fb9jIWlnva9ljVMgujoursYGrRQ8P7UDoNEm/QAYmvTmbgAxXQi+ySkQ5eXlQUkOHQeb6/1Zxn9KKwBuxUtL3534Wd9aUkB84fYC9A0wgweeRVTPxTK3CkPgkuV99QOidntreY1vzyhLmwE9ptUDSHM9mB3G0dXjXOV5OByoBPmixSoNCHwl2iSLAMWItakCIu0AGIYaQHR3XHicqWwBPIIONqxAYOHG70aM2JgqIG66lSAFMxj+DhZJRzOzR1bj+2IpTnnyQDNPjzoQbKrMAiXwiBrhEk2ycL4XuGk8wPAEIycgigvz3vFf+WSdHY+gWQPHf2XoH+1bhcE2Ir/pPMCqYQyPWIB25mBI64jpNDxA/+LsBei7A5354UQ3odJmj5CERDHiVRj7iQUw8uiEvMx90joEulnmKK/wVNb72p7Ytq3tK2bFYpUJiKIlC/4+emT2k3GAiNU9gp5WAOjMHhcopkGrDUFJ3QUg1tkFYtasWaFUAJFWALTX0bsXgB58GobChqAsdgOIp2p9u74a8bqiEAwgsI54AtUroyymovQKk9IPQFgXKlEwmwogXsEnOUdAYB2hKKr4J4C0/Z2RBDoFQHbJUspmDjVLwoEG90GP/5EypiQjkk1xCoSum6NDwbgA4OhJgVIhk2IeJcQdnbmZ+kYUV+XmXht9a/YLOPicB2M3ocGAgNB185gEhXQbTKT+xbgAZAjZj0nF/Kkpk8kipz+LgT3RGF6+ZP7RMSNznjaAwH7gYwvXfh5R62t7hr4sW9owXbfwbRXortkQ0TBMiOvOLpe/U2GeS/T1Uk9ZkmCRgo3aAeQEBLofxZ2BEx9duF6jslAxDjgWgWYOhhoQuDY3ySWzFQCiVlFEY2lh3jkSrenGw5cwMYwukQ1UFyslXDTU7WilBQcuSBhJvFS8OP+nxtONyrFIkjuZe5KkspVRgDDEKvDQk3DzWpi/g6vKWjy/YFQi31y8OG+t6TmiGHcIUGvOxQlkJifgd9O9nQhOKSZQVC8pyD+WKQV/qHBBMeK3EHHeIkaGZndxIX7FhfI6tC001QtddxMpspgQAKHwo+hGlyKMNDmrM/hN4+FG57aBYGwSdo1fN+lzWdfdRIosJgRAydDm1lOmrqPwNfdh03PSRXz+8tLhJ95uwqFoBQJCN+Cnjf3oCvBTvbpHrzWoCQHQ7961Gx0oh7qL6puavmymJVO+xe8fxYJSTX1j24+3NjV9zQkQdJSGN4wvRPwVyI4GRLude4MJASDDFK7u7jc1CTaFKa6FyRht7qMfYt6BcfyyEpT31Ptan3UCxIqluSc+OP3ec+i/1cyXdCWdzbRYZVsAjB2R8z4X3MzQhbe1tnZ78/hYjB3TObsTb7MPiJptLWPteMS4CXfdDlnzzfJIV9LZTItVtgUAzdFCUqv6eQFjd3AmP5fiGUHCNKYBgdtpe+t9O39S59s5LhYQJJt06O3TayLpSLrq64pYdvfRbQFArc+eOv4usi34QYaeuFiKq+6r1q9fb5uP0ZXyIXLwU3z7xxzOPsQvzLd3jzIRpJfwbzQYGpFAkEySjci/lHjpiXhs0XU1aHHzhNHX3Luhqek2EZK3Q8q9Ybq4BCbrigryGrFgMRsRbhKnRIaMHT9toiSLYqzwFuNtjkFzq14qaLTTq8fCZPsHp47+9xsTJy+CsE2g9X1URae3uUtZUrRw4UdxRParsgrqVxntoWFby4OKxOvQse8EB4p8DJWfOXvqWCMMImUdJ9tACHaa/osEMudCyG2GINIBF0SKiwrz3zBodnLHANB4bGhsXY3s1xAwNCxEXMLpzs/xXyBVA7khbhOIsNje0jU434+KHs17zakXOh67JMDLglsoYkO2P6wJH4G6X2Z2qhsHMjuQB61cuuAkprfnJYnNQWT4BWT8Bz+85KgJOvCXSSenxhM3xx5gqFBTsz9Dzrr6NPR6HjSTJ2iKnoGnvKpKnsaSgrnWk1uDha2cFlyIO7TBKcfPunvFVh1TZ1f2BrplZouhpVHSABAfOtbuFt4ViOTrzTFBlxEC7ThWjX9SmPhzINP1L7tDg6Y3jz80Xmb8YQTGR2HkJPB063y1jMY87gStz+A9tVgmB8x1TsoDAoAE0ZgdN3HqTDB6Ed5wD0jWYUWuexGB6zi84m/Yor0vKewcl1mHyiRtCElMzRQKy1FlNho7u2/Blb+DeDIZ/ehzmFVHBFl+GEx/dvb0ewdoyKBN0snKPGlGdJyNi+mPwRtKwcR8iGHlSQcfXdpPsB6tkmtX22iLTT+rm2tN9D/n8darXSrbXFiYaz01MrezXU4ZACSRDjG6mHuKLDiusuGbf+9UOVAZ5EFwd9aGc4HqLBY8RjtDkpeKNFDlouqg/SvMhcsTmCRht4Z/YhCClrd009PuiS0MFJ9j0XMSfdqZqu4ePXL4GbvL26hKxSDeEADMsrZu3T1ccQfu5EKagXH9bRg1AcbREBmGnxHYgihfAUjnAdYZxIt3BVePyEHPyWXL5l0280t1+f+5FIAxQDyRDAAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - identity and access
  - security
  links:
  - name: Verify Product Information
    url: https://www.ibm.com/products/verify-saas
  - name: Verify Documentation
    url: https://www.ibm.com/docs/en/security-verify
  maintainers:
  - email: isamdev@au1.ibm.com
    name: Verify Development Team
  maturity: stable
  minKubeVersion: 1.17.0
  provider:
    name: IBM
    url: https://www.ibm.com
  version: 0000.0000.0000
