apiVersion: ibm.com/v1
kind: IBMSecurityVerify

metadata:
  name: ibmsecurityverify-sample

spec:
  # The name of the secret which contains the IBM Security Verify
  # tenant information.
  tenantSecret: test-tenant.verify.ibm.com
  
  # The root URL of the Nginx Ingress controller.
  ingressRoot: https://my-nginx-ingress.apps.acme.ibm.com

