apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "ibm.com/v1alpha1",
          "kind": "VerifyTenant",
          "metadata": {
            "name": "verifytenant-sample"
          },
          "spec": {
            "client_id": "abdc1234",
            "client_secret": "abcd1234",
            "company_name": "IBM",
            "contact_email": "lgleeson@au1.ibm.com",
            "integration": "CP4S",
            "oidc_client_version": 1,
            "supertenant": "super.tenant.ibmcloudsecurity.com",
            "target_secret": "verify-tenant",
            "tenant": "verifyoperatortest"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.8.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: verify-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: VerifyTenant
      name: verifytenants.ibm.com
      version: v1alpha1
      resources:
        - kind: Secret
          name: ""
      specDescriptors:
        - path: tenant
          description: Nane of Verify tenant to be created
          displayName: Tenant
          x-descriptors:
            - urn:alm:descriptor:com.tectonic.ui:text
        - path: supertenant
          description: Domain name of the Super Tenant which will provision the Verify tenant
          displayName: SuperTenant
          x-descriptors:
            - urn:alm:descriptor:com.tectonic.ui:text
        - path: client_id
          description: OIDC credential for creating new Tenants
          displayName: SuperTenant OIDC client Id
          x-descriptors:
            - urn:alm:descriptor:com.tectonic.ui:text
        - path: client_secret
          description: OIDC credential for creating new Tenants
          displayName: SuperTenant OIDC client secret
          x-descriptors:
            - urn:alm:descriptor:com.tectonic.ui:text
        - path: company_name
          description: Contact company for Tenant
          displayName: Company Name
          x-descriptors:
            - urn:alm:descriptor:com.tectonic.ui:text
        - path: contact_email
          description: Contact email address for Verify tenant
          displayName: Contact Email
          x-descriptors:
            - urn:alm:descriptor:com.tectonic.ui:text
        - path: integration
          description: Verify Integration type.
          displayName: Verify Integration Type
          x-descriptors:
            - urn:alm:descriptor:com.tectonic.ui:text
        - path: oidc_client_version
          description: Version of Tenant OIDC client created
          displayName: Tenant OIDC client version
          x-descriptors:
            - urn:alm:descriptor:com.tectonic.ui:number
        - path: target_secret
          description: Name of the Kubernetes Secret to be created
          displayName: Target Secret
          x-descriptors:
            - urn:alm:descriptor:com.tectonic.ui:text
        - path: target_nmespaces
          description: Namespaces which the Kubernetes Secret will be created in
          displayName: Target Namespaces
      statusDescriptors:
        - path: version
          description: OIDC client version deployed
          displayName: Deployed OIDC client version
          x-descriptors:
            - 'urn:alm:descriptor:com.tectonic.ui:number'
  description: Create and manage IBM Security Verify tenant
  displayName: Verify Tenant Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ibm.com
          resources:
          - verifytenants
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ibm.com
          resources:
          - verifytenants/finalizers
          verbs:
          - update
        - apiGroups:
          - ibm.com
          resources:
          - verifytenants/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: verify-operator-controller-manager
      deployments:
      - name: verify-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: lgleeson/verify-operator:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 100m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 100Mi
                securityContext:
                  allowPrivilegeEscalation: false
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              securityContext:
                runAsNonRoot: true
              serviceAccountName: verify-operator-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: verify-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ibm
  - verify
  - security
  links:
  - name: Verify Operator
    url: https://verify-operator.domain
  maturity: alpha
  provider:
    name: IBM
  version: 0.0.1
  webhookdefinitions:
  - admissionReviewVersions:
    - v1alpha1
    - v1beta1
    containerPort: 443
    deploymentName: verify-operator-controller-manager
    failurePolicy: Fail
    generateName: vverifytenant.kb.io
    rules:
    - apiGroups:
      - ibm.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - verifytenants
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-ibm-com-v1alpha1-verifytenant
  - admissionReviewVersions:
    - v1
    containerPort: 443
    conversionCRDs:
    - verifytenants.ibm.com
    deploymentName: verify-operator-controller-manager
    generateName: cverifytenants.kb.io
    sideEffects: None
    targetPort: 9443
    type: ConversionWebhook
    webhookPath: /convert
