on: [push]
jobs:
  iag_operator:
    runs-on: ubuntu-latest
    name: Job to build demo IAG operator
    steps:
      - name: Cache Operator SDK
        id: cache-operator-sdk
        uses: actions/cache@v2
        with:
          path: ~/.local/bin/operator-sdk
          key: operator-sdk
      - name: Fetch Operator SDK
        id: fetch-operator-sdk
        run: |
          SDK_EXISTS=true
          if ! [ -f $HOME/.local/bin/operator-sdk ]; then
            SDK_EXISTS=false
            echo "SDK file not found"
          fi
          if [ "$SDK_EXISTS" == "true" ]; then
            chmod +x $HOME/.local/bin/operator-sdk
            echo "$HOME/.local/bin" >> $GITHUB_PATH
            SDK_VERSION=$( operator-sdk version | sed -e 's/.*version: "\(v[0-9.]*\)".*/\1/' )
              echo "SDK Version found: $SDK_VERSION"
          fi
          RELEASE_VERSION=$( curl -ksS https://api.github.com/repos/operator-framework/operator-sdk/releases/latest | 
                  jq -r '.tag_name' )
          if [ "$SDK_EXISTS" == "false" ] || [ "$SDK_VERSION" != "$RELEASE_VERSION" ]; then
            mkdir -p $HOME/.local/bin
            echo "Fetching new operator-sdk: $RELEASE_VERSION"
            RELEASE_URL=$( curl -ksS https://api.github.com/repos/operator-framework/operator-sdk/releases/latest | 
                  jq -r '.assets[] | select(.name=="operator-sdk_linux_amd64") | .browser_download_url' )
            curl -ksSL $RELEASE_URL -o ${HOME}/.local/bin/operator-sdk
            chmod +x ${HOME}/.local/bin/operator-sdk
          else
            echo "Using cached operator-sdk $SDK_VERSION"
          fi
      - name: Restore GO cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Operator
        id: build-operator
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          chmod +x $HOME/.local/bin/operator-sdk
          #make manifests
          #make generate
          make test
          #make bundle
          make docker-build

